version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/data/mongodb
  mysql:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: lactapp_dev
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_data_container:/var/lib/mysql
volumes:
  mongodb_data_container:
  mysql_data_container: